import sqlite3
import json
import os
from datetime import datetime

DB_PATH = os.path.join(os.path.dirname(__file__), "news_intelligence.db")

def init_db():
    """
    Initializes the SQLite database with Structured Tables.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # 1. Articles Table (Metadata + Content)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS articles (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        text TEXT NOT NULL,
        link TEXT UNIQUE,
        source TEXT,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        sector TEXT,
        topic TEXT,
        sentiment TEXT,
        urgency TEXT,
        market_impact TEXT,
        investor_relevance TEXT,
        summary TEXT,
        video_script TEXT,
        is_processed BOOLEAN DEFAULT 0
    )
    """)

    # 2. User Memory Table (Persistent Profile)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS user_profile (
        id TEXT PRIMARY KEY,
        user_type TEXT,
        sector_interest TEXT, -- JSON string
        topic_interest TEXT,   -- JSON string
        sentiment_preference TEXT -- JSON string
    )
    """)

    conn.commit()
    conn.close()
    print(f"  📂 [DATABASE]: SQLite initialized at {DB_PATH}")

def save_articles(articles):
    """
    Saves a list of articles to the database, skipping duplicates.
    Also creates embeddings for successfully saved articles safely.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    saved_count = 0
    new_articles_for_embedding = []
    
    for article in articles:
        try:
            # Generate a simple ID or use the link
            article_id = article.get("link", article.get("title", ""))
            
            cursor.execute("""
            INSERT OR IGNORE INTO articles (id, title, text, link, source, timestamp)
            VALUES (?, ?, ?, ?, ?, ?)
            """, (
                article_id,
                article.get("title"),
                article.get("text"),
                article.get("link"),
                article.get("source", "RSS"),
                datetime.now().isoformat()
            ))
            if cursor.rowcount > 0:
                saved_count += 1
                try:
                    # Delay import so it doesn't break module initialization
                    from backend.utils.search_text import build_search_text
                    search_content = build_search_text(article)
                    new_articles_for_embedding.append((article_id, search_content))
                except ImportError:
                    try:
                        from utils.search_text import build_search_text
                        search_content = build_search_text(article)
                        new_articles_for_embedding.append((article_id, search_content))
                    except Exception as e:
                        pass # Ignore if we can't build search text
        except Exception as e:
            print(f"Error saving article: {e}")

    conn.commit()
    conn.close()
    print(f"  📥 [DATABASE]: {saved_count} new articles stored.")
    
    # Store embedding safely
    if new_articles_for_embedding:
        try:
            print(f"  🧠 [DATABASE]: Vectorizing {len(new_articles_for_embedding)} new articles...")
            from backend.database.vector_store import vector_store
            vector_store.add_articles(new_articles_for_embedding)
        except ImportError:
            try:
                from database.vector_store import vector_store
                vector_store.add_articles(new_articles_for_embedding)
            except Exception as e:
                print(f"  ⚠️ [WARNING]: FAISS Embedding skipped. Error: {e}")

def get_latest_news(limit=50):
    """
    Retrieves the most recent unstructured news from the database for processing.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    cursor.execute("SELECT * FROM articles WHERE is_processed = 0 ORDER BY timestamp DESC LIMIT ?", (limit,))
    rows = cursor.fetchall()
    
    conn.close()
    return [dict(row) for row in rows]

def update_article_intelligence(article_id, analysis, summary, video_script):
    """
    Updates an article with the intelligence generated by the agents.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    cursor.execute("""
    UPDATE articles 
    SET sector = ?, topic = ?, sentiment = ?, urgency = ?, market_impact = ?, investor_relevance = ?, 
        summary = ?, video_script = ?, is_processed = 1
    WHERE id = ?
    """, (
        analysis.get("sector", "unknown"),
        analysis.get("topic", "policy"),
        analysis.get("sentiment", "neutral"),
        analysis.get("urgency", "medium"),
        analysis.get("market_impact", "medium"),
        analysis.get("investor_relevance", "medium"),
        summary,
        video_script,
        article_id
    ))
    
    conn.commit()
    conn.close()

def search_articles(query, limit=10):
    """
    Searches historical news articles using keywords as fallback.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    # Simple keyword search on Title and Text
    search_query = f"%{query}%"
    cursor.execute("""
    SELECT * FROM articles 
    WHERE (title LIKE ? OR text LIKE ?) 
    ORDER BY timestamp DESC LIMIT ?
    """, (search_query, search_query, limit))
    
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]

def get_articles_by_ids(article_ids):
    """
    Fetches articles by their exact SQLite string IDs.
    Returns them in the same order as the input list.
    """
    if not article_ids:
        return []
        
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    placeholders = ",".join("?" for _ in article_ids)
    cursor.execute(f"SELECT * FROM articles WHERE id IN ({placeholders})", article_ids)
    rows = cursor.fetchall()
    conn.close()
    
    article_dict = {row["id"]: dict(row) for row in rows}
    ordered_articles = [article_dict[aid] for aid in article_ids if aid in article_dict]
    return ordered_articles

# Initialize on import
init_db()
